name: 'GitHub Action for checking empty strings in an Xcode project'
description: 'A tool to ensure missing translations are not merged into an Xcode project.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'align-left'
